import { vi } from 'vitest';

export const mockGl = {
    createBuffer: vi.fn(() => ({})),
    bindBuffer: vi.fn(),
    bufferData: vi.fn(),
    createVertexArray: vi.fn(() => ({})),
    bindVertexArray: vi.fn(),
    enableVertexAttribArray: vi.fn(),
    vertexAttribPointer: vi.fn(),
    createProgram: vi.fn(() => ({})),
    attachShader: vi.fn(),
    linkProgram: vi.fn(),
    getProgramParameter: vi.fn(() => true),
    useProgram: vi.fn(),
    getAttribLocation: vi.fn(() => 0),
    getUniformLocation: vi.fn(() => 0),
    uniform1f: vi.fn(),
    uniform1i: vi.fn(),
    uniform2f: vi.fn(),
    uniform4fv: vi.fn(),
    uniformMatrix4fv: vi.fn(),
    createTexture: vi.fn(() => ({})),
    bindTexture: vi.fn(),
    texParameteri: vi.fn(),
    texImage2D: vi.fn(),
    activeTexture: vi.fn(),
    drawElements: vi.fn(),
    clear: vi.fn(),
    depthMask: vi.fn(),
    enable: vi.fn(),
    disable: vi.fn(),
    blendFunc: vi.fn(),
    createShader: vi.fn(() => ({})),
    shaderSource: vi.fn(),
    compileShader: vi.fn(),
    getShaderParameter: vi.fn(() => true),
    deleteShader: vi.fn(),
    deleteProgram: vi.fn(),
    bindAttribLocation: vi.fn(),
    ARRAY_BUFFER: 0,
    STATIC_DRAW: 0,
    FLOAT: 0,
    TRIANGLES: 0,
    UNSIGNED_SHORT: 0,
    RGBA: 0,
    UNSIGNED_BYTE: 0,
    TEXTURE_2D: 0,
    TEXTURE_WRAP_S: 0,
    TEXTURE_WRAP_T: 0,
    TEXTURE_MIN_FILTER: 0,
    TEXTURE_MAG_FILTER: 0,
    CLAMP_TO_EDGE: 0,
    LINEAR: 0,
    BLEND: 0,
    SRC_ALPHA: 0,
    ONE_MINUS_SRC_ALPHA: 0,
    VERTEX_SHADER: 0,
    FRAGMENT_SHADER: 0,
    COMPILE_STATUS: 0,
};

export const vec3 = {
    create: vi.fn(() => [0, 0, 0]),
    fromValues: vi.fn((x, y, z) => [x, y, z]),
};

export const mat4 = {
    create: vi.fn(() => []),
    lookAt: vi.fn(),
    perspective: vi.fn(),
};
