import type { GameExports, GameStateSnapshot } from '@quake2ts/game';
import { createGameStateSnapshotFactory } from './factories.js';
import { vi } from 'vitest';

export function createMockGameExports(overrides?: Partial<GameExports>): GameExports {
  return {
    spawnWorld: vi.fn(),
    entities: {} as any, // Mock EntitySystem if needed
    sound: vi.fn(),
    soundIndex: vi.fn().mockReturnValue(0),
    centerprintf: vi.fn(),
    time: 0,
    deathmatch: false,
    skill: 1,
    rogue: false,
    xatrix: false,
    coop: false,
    friendlyFire: false,
    random: {
      getState: vi.fn(),
      setState: vi.fn(),
      random: vi.fn().mockReturnValue(0),
      randomInt: vi.fn().mockReturnValue(0),
      randomFloat: vi.fn().mockReturnValue(0),
      randomVector: vi.fn().mockReturnValue({ x: 0, y: 0, z: 0 }),
      randomDirection: vi.fn().mockReturnValue({ x: 0, y: 0, z: 0 }),
      randomPointInSphere: vi.fn().mockReturnValue({ x: 0, y: 0, z: 0 }),
      crandom: vi.fn().mockReturnValue(0),
    } as any,
    trace: vi.fn().mockReturnValue({
      allsolid: false,
      startsolid: false,
      fraction: 1,
      endpos: { x: 0, y: 0, z: 0 },
      plane: null,
      surfaceFlags: 0,
      contents: 0,
      ent: null,
    }),
    multicast: vi.fn(),
    unicast: vi.fn(),
    configstring: vi.fn(),
    serverCommand: vi.fn(),
    setLagCompensation: vi.fn(),
    createSave: vi.fn().mockReturnValue({}),
    loadSave: vi.fn(),
    serialize: vi.fn().mockReturnValue({}),
    loadState: vi.fn(),
    clientConnect: vi.fn().mockReturnValue(true),
    clientBegin: vi.fn().mockReturnValue({} as any),
    clientDisconnect: vi.fn(),
    clientThink: vi.fn(),
    respawn: vi.fn(),
    setGodMode: vi.fn(),
    setNoclip: vi.fn(),
    setNotarget: vi.fn(),
    giveItem: vi.fn(),
    damage: vi.fn(),
    teleport: vi.fn(),
    registerHooks: vi.fn().mockReturnValue(() => {}),
    hooks: {} as any,
    setSpectator: vi.fn(),
    registerEntitySpawn: vi.fn(),
    unregisterEntitySpawn: vi.fn(),
    getCustomEntities: vi.fn().mockReturnValue([]),
    init: vi.fn().mockReturnValue({
      frame: 0,
      timeMs: 0,
      state: createGameStateSnapshotFactory(),
    }),
    shutdown: vi.fn(),
    frame: vi.fn().mockReturnValue({
      frame: 1,
      timeMs: 100,
      state: createGameStateSnapshotFactory(),
    }),
    ...overrides,
  };
}
